FROM maven:3.9.6-eclipse-temurin-21-alpine

SHELL ["/bin/bash", "-c"]

ONBUILD COPY ./app /app

ONBUILD WORKDIR /app

ONBUILD RUN mvn dependency:resolve

ONBUILD RUN mvn package

CMD ["java", "-jar", "/app/target/app.jar"]