jenkins:
  systemMessage: "Welcome Whanos folks\n\n"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          name: Admin
          password: // Insert Password when about to deploy

tool:
  git:
    installations:
      - name: "git"
        home: "/usr/bin/git"

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
  - file: "${JENKINS_HOME}/config/job_dsl.groovy"
